create table patients (
  patient_id serial not null primary key,
  first_name character varying not null,
  patient_age integer not null,
  patient_gender character varying not null,
  patient_address text,
  patient_phone_number character varying,
  emergency_contact_name text,
  emergency_contact_phone text,
  patient_email text,
  insurance_provider text,
  insurance_policy_number text,
  medical_history text,
  allergies text,
  current_medications text,
  next_visit_date date default now(),
  patient_clinical_data text,
  treatment_plan text,
  notes text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone,
  deleted_at timestamp with time zone,
  last_name character varying not null,
  national_id_number character varying not null,
  coverage_percentage numeric,
  patient_age_unit character varying not null
);
